[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --cov=app --cov-report=term-missing --cov-report=xml:../benchmark/results/coverage/coverage.xml --cov-report=html:../benchmark/results/coverage/htmlcov --cov-fail-under=0
