"""Initial migration

Revision ID: 0641deeed155
Revises: 
Create Date: 2026-06-26 16:03:17.650215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0641deeed155'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicalorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_system', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('modality', sa.Enum('CT', 'MR', 'US', 'DX', 'MG', 'XA', 'NM', 'PT', name='modality'), nullable=False),
    sa.Column('origin_service', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('patient_location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('study_setting', sa.Enum('BEDSIDE', 'SERVICE', name='ordersetting'), nullable=False),
    sa.Column('diagnosis', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('observations', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requesting_physician', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('study_instance_uid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('sent_to_orthanc', sa.Boolean(), nullable=False),
    sa.Column('patient_lastname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('patient_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('patient_pseudonym', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('patient_dni', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('patient_dob', sa.Date(), nullable=False),
    sa.Column('patient_sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sex'), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('triage_priority', sa.Enum('CRITICAL', 'URGENT', 'PRIORITY', 'ROUTINE', name='medicalpriority'), nullable=False),
    sa.Column('order_state', sa.Enum('PENDING', 'PROCESS', 'FINALIZED', 'CANCELLED', name='orderstate'), nullable=False),
    sa.Column('triaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('was_notified', sa.Boolean(), nullable=False),
    sa.Column('criterios_evaluados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicalorder_diagnosis'), 'medicalorder', ['diagnosis'], unique=False)
    op.create_index(op.f('ix_medicalorder_external_id'), 'medicalorder', ['external_id'], unique=True)
    op.create_index(op.f('ix_medicalorder_patient_location'), 'medicalorder', ['patient_location'], unique=False)
    op.create_index(op.f('ix_medicalorder_study_setting'), 'medicalorder', ['study_setting'], unique=False)
    op.create_table('systemsettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('notify_priority', sa.Boolean(), nullable=False),
    sa.Column('triage_critical_threshold', sa.Integer(), nullable=False),
    sa.Column('triage_urgent_threshold', sa.Integer(), nullable=False),
    sa.Column('triage_priority_threshold', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triagerule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('field', sa.Enum('MODALITY', 'DIAGNOSIS', 'ORIGIN_SERVICE', 'PATIENT_LOCATION', 'IS_URGENT', name='triagefield'), nullable=False),
    sa.Column('operator', sa.Enum('EQUALS', 'CONTAINS', 'STARTSWITH', name='triageoperator'), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacionemitida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_order_id', sa.Integer(), nullable=False),
    sa.Column('pseudonym_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('payload_sent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['medical_order_id'], ['medicalorder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacionemitida_medical_order_id'), 'notificacionemitida', ['medical_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificacionemitida_medical_order_id'), table_name='notificacionemitida')
    op.drop_table('notificacionemitida')
    op.drop_table('triagerule')
    op.drop_table('systemsettings')
    op.drop_index(op.f('ix_medicalorder_study_setting'), table_name='medicalorder')
    op.drop_index(op.f('ix_medicalorder_patient_location'), table_name='medicalorder')
    op.drop_index(op.f('ix_medicalorder_external_id'), table_name='medicalorder')
    op.drop_index(op.f('ix_medicalorder_diagnosis'), table_name='medicalorder')
    op.drop_table('medicalorder')
    # ### end Alembic commands ###
